### ISSUE TITLE
gfx glitches during loading

### ISSUE THREAD

**Issue by pkali** [drunkeneye/MAFIA.A8#127]
this is very minor, but could be possibly fixed - during loading DL is getting overwritten and screen glitches. 
simple fix - disable screen DMA by mva #0 DMACTL, sta #DMACTLS
(sta DMACTL will get canceled in VBV, sta DMACTLS might be ineffective because it is copied to DMACTLS during deferred VBV, turned off during transmission)

**Comment by drunkeneye** [comment]
thanks! 

but not sure where and how exactly to implement that.
i have a blank_DLI, so actually could call this before any 
loading, but did not bother to do so (i like screen glitches,
especially the ones when starting the game).

will take a look these days.

**Comment by pkali** [comment]
i fully understand that glitching is fun, the issue is that some glitches lead to unstable loading, because a random DL can introduce timing issues.
I do not think this is the case here, but it is a real thing.

**Comment by drunkeneye** [comment]
yes, true. but it never crashed at loading ;)
i will look into it soon.

besides, funny thing, the title and the main XEX have the exact same DL routines
at the very same addresse, so loading it technically should never alter the DL/DLIs.
maybe thats why i never saw it crashing

**Comment by drunkeneye** [comment]
fixed in latest version.
(although not by using NMI, but setting DLI to blank, works for now)
