### ISSUE TITLE
The money grows in an uncontrolled way.

### ISSUE THREAD

**Issue by perinoid** [drunkeneye/MAFIA.A8#66]
I think, there is a bug in the release version (Polish, at least). After initial parameter settings, when the real game starts, the money is multipied by approx. 600 times. For instance, the game first randomly assigns $9250 and in the game it becomes $5550000. It kind of looks like a not-removed debug feature.
![image](https://github.com/user-attachments/assets/318f0b98-d733-4f15-8f7c-5183a3111c6d)
![image](https://github.com/user-attachments/assets/2fa1dafd-e2df-4eb0-995c-e380a3ba29e4)

**Comment by drunkeneye** [comment]
thanks for reporting!

yes, since the game is yet in testing phase, the debug code is still there.

**Comment by drunkeneye** [comment]
ah, wait, if you downloaded the release here, please be aware that this is an old version
(where the money is added automatically). there will be a release very soon.... please stay put
or use the silly venture 2024 SE version...

**Comment by perinoid** [comment]
OK, Thanks!
By the way - in this version we spotted another bug - after a player was killed by the police, he was prompted, that he still can bribe the cops 'cause he's only arrested. So - is he dead or not? I hope, it's already fixed.

**Comment by drunkeneye** [comment]
well... in this game, nobody ever dies ;)
you can regard it as a bug, but its really a feature...

we will change it to "is done" instead of "dead" in the next version,
then its ambigous.

**Comment by drunkeneye** [comment]
i think we can close this now. money problem was a wrong version, 
dying is 'out of option' (except for victims and not paying customers).
